import './enhanced-generic-detection.test'
import './advanced-circular-reference.test'
/* import './main.test'
import './integration.test'
import './plain.test'
import './optional-properties.test'
import './generic-types.test'
import './enum.test'
import './circular-reference.test'
import './ref-pattern.test'
import './singleton-behavior.test'
import './enhanced-generic-detection.test'
// import './socket-io-external-types.test' */
